### ISSUE TITLE
隐藏接口中的session

### ISSUE THREAD

**Issue by WhiteHunterW** [xiaoymin/blog-comments#148]
`
@PostMapping(value = "/nais/nn")  

@ApiOperation(value = "保存NAIS数据")

@ApiImplicitParam(name = "caseNumber",value = "案例编号",required = true,dataType = "String",paramType = "query")

 public ResultVo saveNewNais(@RequestParam(value = "caseNumber") String caseNumber, HttpSession session){...}`

请问怎么才能隐藏session,填参数时,session里面所有的参数都会被列出来,默认是选中了所有的参数,每次都要手动取消全选,重新选择需要的参数

**
![one](https://user-images.githubusercontent.com/47691709/68282289-606b9d00-00b4-11ea-958d-28f3ea3e5d46.png)
![two](https://user-images.githubusercontent.com/47691709/68282295-63668d80-00b4-11ea-8fbc-57708de4e375.png)

**
swagger-bootstrap-ui 是1.9.5
试过了@ApiOperationSupport

**Comment by xiaoymin** [comment]
参考一下这篇博客：https://www.xiaominfo.com/2019/06/03/springfox-21/
