### ISSUE TITLE
knife4j聚合geteway，是否可以将basePath去掉呢？

### ISSUE THREAD

**Issue by literatureandyou** [xiaoymin/blog-comments#163]
![微信截图_20200718154920](https://user-images.githubusercontent.com/39126967/87847977-b44ea700-c90e-11ea-8112-94ac5f963473.png)

knife4j聚合geteway，是否可以将basePath去掉呢？

**Comment by literatureandyou** [comment]
![2](https://user-images.githubusercontent.com/39126967/87848043-245d2d00-c90f-11ea-832c-5c7c62bae2f2.png)

**Comment by Greenhillsliu** [comment]
求助  一样的问题

**Comment by Greenhillsliu** [comment]
I  have resolved this problem;
step 1:
@Component
public class SwaggerHeaderFilter extends AbstractGatewayFilterFactory {
    private static final String HEADER_NAME = "X-Forwarded-Prefix";

    private static final String URI = "/v2/api-docs";

    @Override
    public GatewayFilter apply(Object config) {
        return (exchange, chain) -> {
            ServerHttpRequest request = exchange.getRequest();
            String path = request.getURI().getPath();
            if (!StringUtils.endsWithIgnoreCase(path,URI )) {
                return chain.filter(exchange);
            }

            ServerHttpRequest newRequest = request.mutate().header(HEADER_NAME, "").build();    //take care here
            ServerWebExchange newExchange = exchange.mutate().request(newRequest).build();
            return chain.filter(newExchange);
        };
    }
}

step 2:
application.yml;
add setting 
spring:
  cloud:
    gateway:
      x-forwarded:
        prefix-enabled: false

**Comment by majingxuan123** [comment]
thank u problem resolved
