### ISSUE TITLE
Knife4jAggregation微服务聚合中间件-基于Nacos方式可以指定namespaceId吗？

### ISSUE THREAD

**Issue by zhangjuncheng-git** [xiaoymin/blog-comments#179]

**Comment by xiaoymin** [comment]
去看文档https://xiaoym.gitee.io/knife4j/documentation/knife4jAggregation.html

**Comment by zhangjuncheng-git** [comment]
> 去看文档https://xiaoym.gitee.io/knife4j/documentation/knife4jAggregation.html

发完就找到了，谢谢了。
